//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//LOADING
export const LOADING_REQUEST = "LOADING_REQUEST";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOADING_FAILURE = "LOADING_FAILURE";

//REGISTER
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

//BOOK GET
export const BOOK_GET_REQUEST = "BOOK_GET_REQUEST";
export const BOOK_GET_SUCCESS = "BOOK_GET_SUCCESS";
export const BOOK_GET_FAILURE = "BOOK_GET_FAILURE";

//DEVICE GET
export const DEVICE_GET_REQUEST = "DEVICE_GET_REQUEST";
export const DEVICE_GET_SUCCESS = "DEVICE_GET_SUCCESS";
export const DEVICE_GET_FAILURE = "DEVICE_GET_FAILURE";

//CLOTHES GET
export const CLOTHES_GET_REQUEST = "CLOTHES_GET_REQUEST";
export const CLOTHES_GET_SUCCESS = "CLOTHES_GET_SUCCESS";
export const CLOTHES_GET_FAILURE = "CLOTHES_GET_FAILURE";

//FREEBOARD GET
export const FREEBOARD_GET_REQUEST = "FREEBOARD_GET_REQUEST";
export const FREEBOARD_GET_SUCCESS = "FREEBOARD_GET_SUCCESS";
export const FREEBOARD_GET_FAILURE = "FREEBOARD_GET_FAILURE";

//NOTICEBOARD GET
export const NOTICEBOARD_GET_REQUEST = "NOTICEBOARD_GET_REQUEST";
export const NOTICEBOARD_GET_SUCCESS = "NOTICEBOARD_GET_SUCCESS";
export const NOTICEBOARD_GET_FAILURE = "NOTICEBOARD_GET_FAILURE";

//
export const BOARD_NEW_REQUEST = "BOARD_NEW_REQUEST";
export const BOARD_NEW_SUCCESS = "BOARD_NEW_SUCCESS";
export const BOARD_NEW_FAILURE = "BOARD_NEW_FAILURE";
