//LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//LOADING
export const LOADING_REQUEST = "LOADING_REQUEST";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOADING_FAILURE = "LOADING_FAILURE";

//REGISTER
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

//FREEBOARD GET
export const BASIC_BOARD_GET_REQUEST = "BASIC_BOARD_GET_REQUEST";
export const BASIC_BOARD_GET_SUCCESS = "BASIC_BOARD_GET_SUCCESS";
export const BASIC_BOARD_GET_FAILURE = "BASIC_BOARD_GET_FAILURE";

//BOARD NEW
export const BOARD_WRITE_REQUEST = "BOARD_WRITE_REQUEST";
export const BOARD_WRITE_SUCCESS = "BOARD_WRITE_SUCCESS";
export const BOARD_WRITE_FAILURE = "BOARD_WRITE_FAILURE";

//BOARD DELETE
export const BOARD_DELETE_REQUEST = "BOARD_DELETE_REQUEST";
export const BOARD_DELETE_SUCCESS = "BOARD_DELETE_SUCCESS";
export const BOARD_DELETE_FAILURE = "BOARD_DELETE_FAILURE";

//BOARD DELETE
export const BOARD_UPDATE_REQUEST = "BOARD_UPDATE_REQUEST";
export const BOARD_UPDATE_SUCCESS = "BOARD_UPDATE_SUCCESS";
export const BOARD_UPDATE_FAILURE = "BOARD_UPDATE_FAILURE";

//BOARD DETAIL
export const BOARD_DETAIL_REQUEST = "BOARD_DETAIL_REQUEST";
export const BOARD_DETAIL_SUCCESS = "BOARD_DETAIL_SUCCESS";
export const BOARD_DETAIL_FAILURE = "BOARD_DETAIL_FAILURE";

//BOARD STATUS
export const BOARD_STATUS_REQUEST = "BOARD_STATUS_REQUEST";
export const BOARD_STATUS_SUCCESS = "BOARD_STATUS_SUCCESS";
export const BOARD_STATUS_FAILURE = "BOARD_STATUS_FAILURE";

//COMMENT GET
export const COMMENT_GET_REQUEST = "COMMENT_GET_REQUEST";
export const COMMENT_GET_SUCCESS = "COMMENT_GET_SUCCESS";
export const COMMENT_GET_FAILURE = "COMMENT_GET_FAILURE";

//COMMENT UPLOAD
export const COMMENT_UPLOAD_REQUEST = "COMMENT_UPLOAD_REQUEST";
export const COMMENT_UPLOAD_SUCCESS = "COMMENT_UPLOAD_SUCCESSE";
export const COMMENT_UPLOAD_FAILURE = "COMMENT_UPLOAD_FAILURE";

//COMMENT UPDATE
export const COMMENT_UPDATE_REQUEST = "COMMENT_UPDATE_REQUEST";
export const COMMENT_UPDATE_SUCCESS = "COMMENT_UPDATE_SUCCESSE";
export const COMMENT_UPDATE_FAILURE = "COMMENT_UPDATE_FAILURE";

//COMMENT UPDATE
export const COMMENT_DELETE_REQUEST = "COMMENT_DELETE_REQUEST";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESSE";
export const COMMENT_DELETE_FAILURE = "COMMENT_DELETE_FAILURE";

//REPLY UPLOAD
export const REPLY_UPLOAD_REQUEST = "REPLY_UPLOAD_REQUEST";
export const REPLY_UPLOAD_SUCCESS = "REPLY_UPLOAD_SUCCESS";
export const REPLY_UPLOAD_FAILURE = "REPLY_UPLOAD_FAILURE";

//IMAGE DELETE
export const IMAGE_DELETE_REQUEST = "IMAGE_DELETE_REQUEST";
export const IMAGE_DELETE_SUCCESS = "IMAGE_DELETE_SUCCESS";
export const IMAGE_DELETE_FAILURE = "IMAGE_DELETE_FAILURE";

//PROFILE GET
export const PROFILE_GET_REQUEST = "PROFILE_GET_REQUEST";
export const PROFILE_GET_SUCCESS = "PROFILE_GET_SUCCESS";
export const PROFILE_GET_FAILURE = "PROFILE_GET_FAILURE";

//PROFILE IMAGE UPDATE
export const PROFILE_IMAGE_UPDATE_REQUEST = "PROFILE_IMAGE_UPDATE_REQUEST";
export const PROFILE_IMAGE_UPDATE_SUCCESS = "PROFILE_IMAGE_UPDATE_SUCCESS";
export const PROFILE_IMAGE_UPDATE_FAILURE = "PROFILE_IMAGE_UPDATE_FAILURE";

//TRADE COMPLET
export const TRADE_COMMENT_GET_REQUEST = "TRADE_COMMENT_GET_REQUEST";
export const TRADE_COMMENT_GET_SUCCESS = "TRADE_COMMENT_GET_SUCCESS";
export const TRADE_COMMENT_GET_FAILURE = "TRADE_COMMENT_GET_FAILURE";

//Purchase Create
export const TRADE_COMPLETE_REQUEST = "TRADE_COMPLETE_REQUEST";
export const TRADE_COMPLETE_SUCCESS = "TRADE_COMPLETE_SUCCESS";
export const TRADE_COMPLETE_FAILURE = "TRADE_COMPLETE_FAILURE";